### PR TITLE
sudo not found in docker image at runtime

### PR DESCRIPTION
**Pull request by mvording**
strip out references to sudo from script... was getting sudo not found errors after having a look why docker build failed

### CODE REVIEW

**Comment by joanbono** [comment]
Hi!!

I'm om holidays at the moment, and for sure, I have no access to a computer 🤷🏽‍♂️

Will check this!!

Thanks for the commit!! Stay tuned!!

**Comment by mvording** [comment]
Removing sudos with sed search+replace eliminated many errors due to base container image not having it.  There were other issues preventing the install working as-is though.

**Comment by joanbono** [comment]
Ok, what about changing the main distro? I mean, switching from `Kali Linux` to `Debian` directly?

Did you try this?

Thanks :)

**Comment by joanbono** [comment]
Hi @mvording , did you try this?

**Comment by joanbono** [comment]
Tested, and working!

**Pull request merged**
