### PR TITLE
Resolve snort version the the latest

### PR DESCRIPTION
**Pull request by rbshadow**
Previous

screenshot from 2017-11-20 11 31 01

Latest

screenshot from 2017-11-20 11 32 28

### CODE REVIEW

**Comment by joanbono** [comment]
Really good catch!

I've fixed this by this way, I thik it's correct to specify the numbers that would appear.:

~~~bash
SNORT=$(echo $(curl -s -k https://www.snort.org | grep "wget" | grep -oP "snort\-\d.\d\.\d{1,3}"))
~~~

Thanks bro!

**Comment by joanbono** [comment]
✅ `FIXED` in commit [`c22f74d`](https://github.com/joanbono/Snorter/commit/c22f74de9172d5fa4bf96200659949f628260035)

**Comment by rbshadow** [comment]
Please do fix for Ubuntu 14.04 also. Thank you :+1:

**Comment by joanbono** [comment]
Done! 😃

**Pull request closed without merging**
